version: '3'

services:
  gridiron-app:
    container_name: gridiron-app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
