version: '3'

services:
  gridiron-db:
    container_name: gridiron-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

  gridiron-service:
    container_name: gridiron-service
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.service
    ports:
      - "8080:8080"
    depends_on:
      - gridiron-db
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      SECRET_KEY: $SECRET_KEY
      SERVER_PORT: 8080