# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /web

# Copy package.json and package-lock.json (if available)
COPY ./web/package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining app source code
COPY ./web .

# Build the React app
RUN npm run build

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the React app
CMD ["npm", "start"]
