version: '3'

services:
  gridiron-db:
    container_name: gridiron-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

  gridiron-rabbitmq:
    container_name: gridiron-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  gridiron-service:
    container_name: gridiron-service
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile.service
    ports:
      - "8080:8080"
    depends_on:
      - gridiron-db
    environment:
      DB_HOST: $DB_HOST_CONTAINER
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      RABBITMQ_HOST: $RABBITMQ_HOST_CONTAINER
      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      RABBITMQ_EXCHANGE_TENANT: tenant-exchange
      SECRET_KEY: $SECRET_KEY
      SERVER_PORT: 8080

  gridiron-web:
    build: 
      context: ../
      dockerfile: ./deployments/Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - .:/app