version: '3'

services:
  gridiron-db:
    container_name: gridiron-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password

  gridiron-app:
    container_name: gridiron-app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - gridiron-db
    environment:
      DB_HOST: gridiron-db
      DB_USER: my_user
      DB_PASSWORD: my_password
      DB_NAME: my_db
      PRIVATE_KEY: $PRIVATE_KEY
      SERVER_PORT: 8080
